// EngineBuildingBlocks/Input/QtKeyMap.cpp

#include <EngineBuildingBlocks/Input/QtKeys.h>

#if (IS_BUILDING_WITH_QT)

#include <Qt>

using namespace EngineBuildingBlocks::Input;

#define AddEntry(specificKey, generalKey)				\
	m_SpecificToGeneral[specificKey] = generalKey;		\
	m_GeneralToSpecific[(int)generalKey] = specificKey;

QtKeyMap::QtKeyMap()
{
	const int size = 512;
	m_GeneralToSpecific.PushBack(-1, static_cast<unsigned>(size));
	for (int i = 0; i < size; i++)
	{
		m_SpecificToGeneral[i] = EngineBuildingBlocks::Input::Keys::Unknown;
	}

	// Adding entries.
	AddEntry(Qt::Key_Space, EngineBuildingBlocks::Input::Keys::Space)
	AddEntry(Qt::Key_Apostrophe, EngineBuildingBlocks::Input::Keys::Apostrophe)
	AddEntry(Qt::Key_Comma, EngineBuildingBlocks::Input::Keys::Comma)
	AddEntry(Qt::Key_Minus, EngineBuildingBlocks::Input::Keys::Minus)
	AddEntry(Qt::Key_Period, EngineBuildingBlocks::Input::Keys::Period)
	AddEntry(Qt::Key_Slash, EngineBuildingBlocks::Input::Keys::Slash)
	AddEntry(Qt::Key_Semicolon, EngineBuildingBlocks::Input::Keys::Semicolon)
	AddEntry(Qt::Key_Equal, EngineBuildingBlocks::Input::Keys::Equal)
	AddEntry(Qt::Key_BracketLeft, EngineBuildingBlocks::Input::Keys::LeftBracket)
	AddEntry(Qt::Key_Backslash, EngineBuildingBlocks::Input::Keys::BackSlash)
	AddEntry(Qt::Key_BracketRight, EngineBuildingBlocks::Input::Keys::RightBracket)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::GraveAccent)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::World1)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::World2)
	AddEntry(Qt::Key_0, EngineBuildingBlocks::Input::Keys::Key0)
	AddEntry(Qt::Key_1, EngineBuildingBlocks::Input::Keys::Key1)
	AddEntry(Qt::Key_2, EngineBuildingBlocks::Input::Keys::Key2)
	AddEntry(Qt::Key_3, EngineBuildingBlocks::Input::Keys::Key3)
	AddEntry(Qt::Key_4, EngineBuildingBlocks::Input::Keys::Key4)
	AddEntry(Qt::Key_5, EngineBuildingBlocks::Input::Keys::Key5)
	AddEntry(Qt::Key_6, EngineBuildingBlocks::Input::Keys::Key6)
	AddEntry(Qt::Key_7, EngineBuildingBlocks::Input::Keys::Key7)
	AddEntry(Qt::Key_8, EngineBuildingBlocks::Input::Keys::Key8)
	AddEntry(Qt::Key_9, EngineBuildingBlocks::Input::Keys::Key9)
	AddEntry(Qt::Key_A, EngineBuildingBlocks::Input::Keys::A)
	AddEntry(Qt::Key_B, EngineBuildingBlocks::Input::Keys::B)
	AddEntry(Qt::Key_C, EngineBuildingBlocks::Input::Keys::C)
	AddEntry(Qt::Key_D, EngineBuildingBlocks::Input::Keys::D)
	AddEntry(Qt::Key_E, EngineBuildingBlocks::Input::Keys::E)
	AddEntry(Qt::Key_F, EngineBuildingBlocks::Input::Keys::F)
	AddEntry(Qt::Key_G, EngineBuildingBlocks::Input::Keys::G)
	AddEntry(Qt::Key_H, EngineBuildingBlocks::Input::Keys::H)
	AddEntry(Qt::Key_I, EngineBuildingBlocks::Input::Keys::I)
	AddEntry(Qt::Key_J, EngineBuildingBlocks::Input::Keys::J)
	AddEntry(Qt::Key_K, EngineBuildingBlocks::Input::Keys::K)
	AddEntry(Qt::Key_L, EngineBuildingBlocks::Input::Keys::L)
	AddEntry(Qt::Key_M, EngineBuildingBlocks::Input::Keys::M)
	AddEntry(Qt::Key_N, EngineBuildingBlocks::Input::Keys::N)
	AddEntry(Qt::Key_O, EngineBuildingBlocks::Input::Keys::O)
	AddEntry(Qt::Key_P, EngineBuildingBlocks::Input::Keys::P)
	AddEntry(Qt::Key_Q, EngineBuildingBlocks::Input::Keys::Q)
	AddEntry(Qt::Key_R, EngineBuildingBlocks::Input::Keys::R)
	AddEntry(Qt::Key_S, EngineBuildingBlocks::Input::Keys::S)
	AddEntry(Qt::Key_T, EngineBuildingBlocks::Input::Keys::T)
	AddEntry(Qt::Key_Z, EngineBuildingBlocks::Input::Keys::U)
	AddEntry(Qt::Key_V, EngineBuildingBlocks::Input::Keys::V)
	AddEntry(Qt::Key_W, EngineBuildingBlocks::Input::Keys::W)
	AddEntry(Qt::Key_X, EngineBuildingBlocks::Input::Keys::X)
	AddEntry(Qt::Key_Y, EngineBuildingBlocks::Input::Keys::Y)
	AddEntry(Qt::Key_Z, EngineBuildingBlocks::Input::Keys::Z)
	AddEntry(Qt::Key_Escape, EngineBuildingBlocks::Input::Keys::Escape)
	AddEntry(Qt::Key_Return, EngineBuildingBlocks::Input::Keys::Enter)
	AddEntry(Qt::Key_Tab, EngineBuildingBlocks::Input::Keys::Tab)
	AddEntry(Qt::Key_Back, EngineBuildingBlocks::Input::Keys::Backspace)
	AddEntry(Qt::Key_Insert, EngineBuildingBlocks::Input::Keys::Insert)
	AddEntry(Qt::Key_Delete, EngineBuildingBlocks::Input::Keys::Delete)
	AddEntry(Qt::Key_Right, EngineBuildingBlocks::Input::Keys::Right)
	AddEntry(Qt::Key_Left, EngineBuildingBlocks::Input::Keys::Left)
	AddEntry(Qt::Key_Down, EngineBuildingBlocks::Input::Keys::Down)
	AddEntry(Qt::Key_Up, EngineBuildingBlocks::Input::Keys::Up)
	AddEntry(Qt::Key_PageUp, EngineBuildingBlocks::Input::Keys::PageUp)
	AddEntry(Qt::Key_PageDown, EngineBuildingBlocks::Input::Keys::PageDown)
	AddEntry(Qt::Key_Home, EngineBuildingBlocks::Input::Keys::Home)
	AddEntry(Qt::Key_End, EngineBuildingBlocks::Input::Keys::End)
	AddEntry(Qt::Key_CapsLock, EngineBuildingBlocks::Input::Keys::CapsLock)
	AddEntry(Qt::Key_ScrollLock, EngineBuildingBlocks::Input::Keys::ScrollLock)
	AddEntry(Qt::Key_NumLock, EngineBuildingBlocks::Input::Keys::NumLock)
	AddEntry(Qt::Key_Print, EngineBuildingBlocks::Input::Keys::PrintScreen)
	AddEntry(Qt::Key_Pause, EngineBuildingBlocks::Input::Keys::Pause)
	AddEntry(Qt::Key_F1, EngineBuildingBlocks::Input::Keys::F1)
	AddEntry(Qt::Key_F2, EngineBuildingBlocks::Input::Keys::F2)
	AddEntry(Qt::Key_F3, EngineBuildingBlocks::Input::Keys::F3)
	AddEntry(Qt::Key_F4, EngineBuildingBlocks::Input::Keys::F4)
	AddEntry(Qt::Key_F5, EngineBuildingBlocks::Input::Keys::F5)
	AddEntry(Qt::Key_F6, EngineBuildingBlocks::Input::Keys::F6)
	AddEntry(Qt::Key_F7, EngineBuildingBlocks::Input::Keys::F7)
	AddEntry(Qt::Key_F8, EngineBuildingBlocks::Input::Keys::F8)
	AddEntry(Qt::Key_F9, EngineBuildingBlocks::Input::Keys::F9)
	AddEntry(Qt::Key_F10, EngineBuildingBlocks::Input::Keys::F10)
	AddEntry(Qt::Key_F11, EngineBuildingBlocks::Input::Keys::F11)
	AddEntry(Qt::Key_F12, EngineBuildingBlocks::Input::Keys::F12)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad0)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad1)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad2)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad3)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad4)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad5)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad6)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad7)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad8)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPad9)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadDecimal)
	AddEntry(Qt::Key_division, EngineBuildingBlocks::Input::Keys::KeyPadDivide)
	AddEntry(Qt::Key_multiply, EngineBuildingBlocks::Input::Keys::KeyPadMultiply)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadSubtract)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadAdd)
	AddEntry(Qt::Key_Enter, EngineBuildingBlocks::Input::Keys::KeyPadEnter)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadEqual)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::LeftShift)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::LeftControl)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::LeftAlt)
	AddEntry(Qt::Key_Super_L, EngineBuildingBlocks::Input::Keys::LeftSuper)
	AddEntry(Qt::Key_Shift, EngineBuildingBlocks::Input::Keys::RightShift)
	AddEntry(Qt::Key_Control, EngineBuildingBlocks::Input::Keys::RightControl)
	AddEntry(Qt::Key_Alt, EngineBuildingBlocks::Input::Keys::RightAlt)
	AddEntry(Qt::Key_Super_R, EngineBuildingBlocks::Input::Keys::RightSuper)
	AddEntry(Qt::Key_Menu, EngineBuildingBlocks::Input::Keys::Menu)
}

#endif